-- ================================================================
--  제주 여행 플랫폼 - 전체 스키마 (도메인별 정리)
--  Oracle DB
-- ================================================================


-- ================================================================
--  1. 회원 도메인
-- ================================================================

CREATE SEQUENCE SEQ_MEMBER_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AUTH_KEY_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TRAVEL_STYLE_NO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 회원
CREATE TABLE MEMBER (
    MEMBER_NO       NUMBER NOT NULL,
    EMAIL           VARCHAR2(100) NOT NULL,
    PASSWORD        VARCHAR2(255) NOT NULL,
    NAME            NVARCHAR2(50) NOT NULL,
    NICKNAME        NVARCHAR2(20) NOT NULL,
    PHONE           VARCHAR2(20),
    GENDER          CHAR(1),
    AGE_RANGE       VARCHAR2(10),
    PROFILE_IMAGE   VARCHAR2(500),
    BIRTH_DATE      DATE,                              -- 생년월일
    INTRO           NVARCHAR2(200),
    MEMBER_TYPE     CHAR(1) DEFAULT 'U' NOT NULL,     -- U:일반회원, A:관리자
    STATUS          CHAR(1) DEFAULT 'A' NOT NULL,      -- A:활성, W:탈퇴
    EMAIL_VERIFIED  CHAR(1) DEFAULT 'N',               -- Y:인증, N:미인증
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_NO),
    CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_MEMBER_NICKNAME UNIQUE (NICKNAME),
    CONSTRAINT UK_MEMBER_PHONE UNIQUE (PHONE),
    CONSTRAINT CHK_MEMBER_TYPE CHECK (MEMBER_TYPE IN ('U', 'A')),
    CONSTRAINT CHK_MEMBER_STATUS CHECK (STATUS IN ('A', 'W')),
    CONSTRAINT CHK_MEMBER_GENDER CHECK (GENDER IN ('M', 'F') OR GENDER IS NULL),
    CONSTRAINT CHK_EMAIL_VERIFIED CHECK (EMAIL_VERIFIED IN ('Y', 'N'))
);

-- 이메일 인증키
CREATE TABLE AUTH_KEY (
    KEY_NO          NUMBER NOT NULL,
    EMAIL           VARCHAR2(100) NOT NULL,
    AUTH_KEY        VARCHAR2(6) NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    EXPIRED_AT      DATE NOT NULL,
    IS_VERIFIED     CHAR(1) DEFAULT 'N' NOT NULL,      -- Y:인증완료, N:미인증
    CONSTRAINT PK_AUTH_KEY PRIMARY KEY (KEY_NO),
    CONSTRAINT CHK_AUTH_VERIFIED CHECK (IS_VERIFIED IN ('Y', 'N'))
);

-- 여행 스타일 코드
CREATE TABLE TRAVEL_STYLE (
    STYLE_NO        NUMBER NOT NULL,
    STYLE_NAME      NVARCHAR2(50) NOT NULL,
    DESCRIPTION     NVARCHAR2(200),
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TRAVEL_STYLE PRIMARY KEY (STYLE_NO),
    CONSTRAINT UK_STYLE_NAME UNIQUE (STYLE_NAME)
);

-- 회원-여행스타일 매핑
CREATE TABLE MEMBER_TRAVEL_STYLE (
    MEMBER_NO       NUMBER NOT NULL,
    STYLE_NO        NUMBER NOT NULL,
    CONSTRAINT PK_MEMBER_TRAVEL_STYLE PRIMARY KEY (MEMBER_NO, STYLE_NO),
    CONSTRAINT FK_MTS_MEMBER FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,
    CONSTRAINT FK_MTS_STYLE FOREIGN KEY (STYLE_NO)
        REFERENCES TRAVEL_STYLE(STYLE_NO) ON DELETE CASCADE
);

CREATE INDEX IDX_MEMBER_EMAIL ON MEMBER (EMAIL);
CREATE INDEX IDX_MEMBER_NICKNAME ON MEMBER (NICKNAME);
CREATE INDEX IDX_MEMBER_STATUS ON MEMBER (STATUS, CREATED_AT DESC);


-- ================================================================
--  2. 숙소 도메인
-- ================================================================

CREATE SEQUENCE SEQ_ACCOM_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ACCOM_IMG_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ACCOM_TAG_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EXTERNAL_LINK_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ACCOM_WISHLIST_NO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 숙소
CREATE TABLE ACCOMMODATION (
    ACCOMMODATION_NO    NUMBER NOT NULL,
    NAME                NVARCHAR2(200) NOT NULL,
    ADDRESS             NVARCHAR2(500) NOT NULL,
    PHONE               VARCHAR2(20),
    PRICE_MIN           NUMBER,
    PRICE_MAX           NUMBER,
    CHECK_IN_TIME       VARCHAR2(5),
    CHECK_OUT_TIME      VARCHAR2(5),
    FACILITIES          NVARCHAR2(2000),
    ACCOMMODATION_TYPE  VARCHAR2(50),                   -- 게스트하우스/호텔/펜션/민박/리조트/한옥/풀빌라/모텔/기타
    REGION              VARCHAR2(50),                    -- 제주시/서귀포시
    LATITUDE            NUMBER(10, 7),
    LONGITUDE           NUMBER(10, 7),
    TOUR_API_ID         VARCHAR2(100),
    RECOMMENDATION_REASON NVARCHAR2(2000),
    THUMBNAIL_URL       VARCHAR2(500),
    VIEW_COUNT          NUMBER DEFAULT 0 NOT NULL,
    STATUS              CHAR(1) DEFAULT 'A' NOT NULL,   -- A:활성, C:폐업
    CREATED_AT          DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT          DATE,
    CONSTRAINT PK_ACCOMMODATION PRIMARY KEY (ACCOMMODATION_NO),
    CONSTRAINT CHK_ACCOM_STATUS CHECK (STATUS IN ('A', 'C')),
    CONSTRAINT CHK_PRICE_RANGE CHECK (PRICE_MIN IS NULL OR PRICE_MAX IS NULL OR PRICE_MIN <= PRICE_MAX),
    CONSTRAINT CHK_ACCOM_REGION CHECK (REGION IN ('제주시', '서귀포시') OR REGION IS NULL),
    CONSTRAINT CHK_ACCOM_TYPE CHECK (ACCOMMODATION_TYPE IN ('게스트하우스', '호스텔', '호텔', '펜션', '민박', '리조트', '한옥', '풀빌라', '모텔', '기타') OR ACCOMMODATION_TYPE IS NULL),
    CONSTRAINT CHK_CHECKIN_FORMAT CHECK (CHECK_IN_TIME IS NULL OR REGEXP_LIKE(CHECK_IN_TIME, '^([0-1][0-9]|2[0-3]):[0-5][0-9]')),
    CONSTRAINT CHK_CHECKOUT_FORMAT CHECK (CHECK_OUT_TIME IS NULL OR REGEXP_LIKE(CHECK_OUT_TIME, '^([0-1][0-9]|2[0-3]):[0-5][0-9]'))
);

-- 숙소 이미지
CREATE TABLE ACCOMMODATION_IMAGE (
    IMAGE_NO            NUMBER NOT NULL,
    ACCOMMODATION_NO    NUMBER NOT NULL,
    IMAGE_URL           VARCHAR2(500) NOT NULL,
    IMAGE_ORDER         NUMBER NOT NULL,
    CREATED_AT          DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ACCOMMODATION_IMAGE PRIMARY KEY (IMAGE_NO),
    CONSTRAINT FK_ACCOM_IMG_ACCOM FOREIGN KEY (ACCOMMODATION_NO)
        REFERENCES ACCOMMODATION(ACCOMMODATION_NO) ON DELETE CASCADE
);

-- 숙소 태그
CREATE TABLE ACCOMMODATION_TAG (
    TAG_NO          NUMBER NOT NULL,
    TAG_NAME        NVARCHAR2(50) NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ACCOMMODATION_TAG PRIMARY KEY (TAG_NO),
    CONSTRAINT UK_ACCOM_TAG_NAME UNIQUE (TAG_NAME)
);

-- 숙소-태그 매핑
CREATE TABLE ACCOMMODATION_TAG_MAP (
    ACCOMMODATION_NO    NUMBER NOT NULL,
    TAG_NO              NUMBER NOT NULL,
    CONSTRAINT PK_ACCOM_TAG_MAP PRIMARY KEY (ACCOMMODATION_NO, TAG_NO),
    CONSTRAINT FK_ATM_ACCOM FOREIGN KEY (ACCOMMODATION_NO)
        REFERENCES ACCOMMODATION(ACCOMMODATION_NO) ON DELETE CASCADE,
    CONSTRAINT FK_ATM_TAG FOREIGN KEY (TAG_NO)
        REFERENCES ACCOMMODATION_TAG(TAG_NO) ON DELETE CASCADE
);

-- 외부 예약 링크 (야놀자, 에어비앤비 등)
CREATE TABLE EXTERNAL_LINK (
    LINK_NO             NUMBER NOT NULL,
    ACCOMMODATION_NO    NUMBER NOT NULL,
    PLATFORM_NAME       VARCHAR2(50) NOT NULL,
    URL                 VARCHAR2(1000) NOT NULL,
    CREATED_AT          DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_EXTERNAL_LINK PRIMARY KEY (LINK_NO),
    CONSTRAINT FK_EXT_LINK_ACCOM FOREIGN KEY (ACCOMMODATION_NO)
        REFERENCES ACCOMMODATION(ACCOMMODATION_NO) ON DELETE CASCADE
);

-- 숙소 위시리스트
CREATE TABLE ACCOM_WISHLIST (
    WISHLIST_NO         NUMBER NOT NULL,
    ACCOMMODATION_NO    NUMBER NOT NULL,
    MEMBER_NO           NUMBER NOT NULL,
    CREATED_AT          DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ACCOM_WISHLIST PRIMARY KEY (WISHLIST_NO),
    CONSTRAINT UK_WISHLIST UNIQUE (ACCOMMODATION_NO, MEMBER_NO),
    CONSTRAINT FK_AW_ACCOM FOREIGN KEY (ACCOMMODATION_NO)
        REFERENCES ACCOMMODATION(ACCOMMODATION_NO) ON DELETE CASCADE,
    CONSTRAINT FK_AW_MEMBER FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
);

CREATE INDEX IDX_ACCOM_REGION_TYPE ON ACCOMMODATION (REGION, ACCOMMODATION_TYPE);
CREATE INDEX IDX_ACCOM_STATUS ON ACCOMMODATION (STATUS, CREATED_AT DESC);
CREATE INDEX IDX_ACCOM_VIEWCOUNT ON ACCOMMODATION (VIEW_COUNT DESC);
CREATE INDEX IDX_WISHLIST_MEMBER ON ACCOM_WISHLIST (MEMBER_NO);


-- ================================================================
--  3. 게시판 도메인
-- ================================================================

CREATE SEQUENCE SEQ_BOARD_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BOARD_IMG_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HASHTAG_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MATE_NO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 게시판 종류
CREATE TABLE BOARD_TYPE (
    BOARD_CODE      VARCHAR2(20) NOT NULL,
    BOARD_NAME      NVARCHAR2(50) NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_BOARD_TYPE PRIMARY KEY (BOARD_CODE),
    CONSTRAINT UK_BOARD_NAME UNIQUE (BOARD_NAME)
);

-- 해시태그
CREATE TABLE HASHTAG (
    HASHTAG_NO      NUMBER NOT NULL,
    TAG_NAME        NVARCHAR2(50) NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_HASHTAG PRIMARY KEY (HASHTAG_NO),
    CONSTRAINT UK_HASHTAG_NAME UNIQUE (TAG_NAME)
);

-- 게시판
CREATE TABLE BOARD (
    BOARD_NO        NUMBER NOT NULL,
    MEMBER_NO       NUMBER NOT NULL,
    BOARD_CODE      VARCHAR2(20) NOT NULL,
    TITLE           NVARCHAR2(100) NOT NULL,
    CONTENT         CLOB NOT NULL,
    VIEW_COUNT      NUMBER DEFAULT 0 NOT NULL,
    STATUS          CHAR(1) DEFAULT 'A' NOT NULL,       -- A:활성, D:삭제, B:차단
    IS_NOTICE       CHAR(1) DEFAULT 'N' NOT NULL,       -- Y:공지, N:일반
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE,
    CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_NO),
    CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,
    CONSTRAINT FK_BOARD_TYPE FOREIGN KEY (BOARD_CODE)
        REFERENCES BOARD_TYPE(BOARD_CODE),
    CONSTRAINT CHK_BOARD_STATUS CHECK (STATUS IN ('A', 'D', 'B')),
    CONSTRAINT CHK_IS_NOTICE CHECK (IS_NOTICE IN ('Y', 'N'))
);

-- 게시판 이미지
CREATE TABLE BOARD_IMAGE (
    IMAGE_NO        NUMBER NOT NULL,
    BOARD_NO        NUMBER NOT NULL,
    IMAGE_URL       VARCHAR2(500) NOT NULL,
    IMAGE_ORDER     NUMBER NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_BOARD_IMAGE PRIMARY KEY (IMAGE_NO),
    CONSTRAINT FK_BOARD_IMG_BOARD FOREIGN KEY (BOARD_NO)
        REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE
);

-- 게시판-해시태그 매핑
CREATE TABLE BOARD_HASHTAG (
    BOARD_NO        NUMBER NOT NULL,
    HASHTAG_NO      NUMBER NOT NULL,
    CONSTRAINT PK_BOARD_HASHTAG PRIMARY KEY (BOARD_NO, HASHTAG_NO),
    CONSTRAINT FK_BH_BOARD FOREIGN KEY (BOARD_NO)
        REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,
    CONSTRAINT FK_BH_HASHTAG FOREIGN KEY (HASHTAG_NO)
        REFERENCES HASHTAG(HASHTAG_NO) ON DELETE CASCADE
);

-- 댓글 (대댓글 포함)
CREATE TABLE COMMENT_TBL (
    COMMENT_NO          NUMBER NOT NULL,
    BOARD_NO            NUMBER NOT NULL,
    MEMBER_NO           NUMBER NOT NULL,
    PARENT_COMMENT_NO   NUMBER,
    CONTENT             CLOB NOT NULL,
    STATUS              CHAR(1) DEFAULT 'A' NOT NULL,   -- A:활성, D:삭제
    CREATED_AT          DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT          DATE,
    CONSTRAINT PK_COMMENT PRIMARY KEY (COMMENT_NO),
    CONSTRAINT FK_COMMENT_BOARD FOREIGN KEY (BOARD_NO)
        REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,
    CONSTRAINT FK_COMMENT_MEMBER FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,
    CONSTRAINT FK_COMMENT_PARENT FOREIGN KEY (PARENT_COMMENT_NO)
        REFERENCES COMMENT_TBL(COMMENT_NO),
    CONSTRAINT CHK_COMMENT_STATUS CHECK (STATUS IN ('A', 'D'))
);

-- 동행 모집 (BOARD 확장)
CREATE TABLE MATE (
    MATE_NO                 NUMBER NOT NULL,
    BOARD_NO                NUMBER NOT NULL,
    TRAVEL_START_DATE       DATE NOT NULL,
    TRAVEL_END_DATE         DATE NOT NULL,
    GENDER_PREFERENCE       CHAR(1),                     -- M:남성, F:여성, A:무관
    AGE_RANGE               VARCHAR2(50),
    MAX_PEOPLE              NUMBER NOT NULL,
    INTERESTS               NVARCHAR2(200),
    RECRUITMENT_STATUS      CHAR(1) DEFAULT 'R' NOT NULL, -- R:모집중, C:모집완료
    CONSTRAINT PK_MATE PRIMARY KEY (MATE_NO),
    CONSTRAINT UK_MATE_BOARD UNIQUE (BOARD_NO),
    CONSTRAINT FK_MATE_BOARD FOREIGN KEY (BOARD_NO)
        REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,
    CONSTRAINT CHK_MATE_STATUS CHECK (RECRUITMENT_STATUS IN ('R', 'C')),
    CONSTRAINT CHK_MATE_PERIOD CHECK (TRAVEL_START_DATE <= TRAVEL_END_DATE),
    CONSTRAINT CHK_MATE_GENDER CHECK (GENDER_PREFERENCE IN ('M', 'F', 'A') OR GENDER_PREFERENCE IS NULL),
    CONSTRAINT CHK_MATE_MAX CHECK (MAX_PEOPLE BETWEEN 1 AND 10)
);

CREATE INDEX IDX_BOARD_CODE_DATE ON BOARD (BOARD_CODE, CREATED_AT DESC);
CREATE INDEX IDX_BOARD_MEMBER ON BOARD (MEMBER_NO);
CREATE INDEX IDX_BOARD_STATUS ON BOARD (STATUS, CREATED_AT DESC);
CREATE INDEX IDX_COMMENT_BOARD_DATE ON COMMENT_TBL (BOARD_NO, CREATED_AT DESC);
CREATE INDEX IDX_COMMENT_MEMBER ON COMMENT_TBL (MEMBER_NO);
CREATE INDEX IDX_COMMENT_PARENT ON COMMENT_TBL (PARENT_COMMENT_NO);


-- ================================================================
--  4. 숙소 후기 도메인
-- ================================================================

CREATE SEQUENCE SEQ_REVIEW_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_IMG_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_VERIFY_NO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 숙소 후기
CREATE TABLE ACCOMMODATION_REVIEW (
    REVIEW_NO               NUMBER NOT NULL,
    ACCOMMODATION_NO        NUMBER NOT NULL,
    MEMBER_NO               NUMBER NOT NULL,
    BOARD_NO                NUMBER,
    RATING                  NUMBER(2, 1) NOT NULL,
    CONTENT                 CLOB NOT NULL,
    CHECK_IN_DATE           DATE,
    CHECK_OUT_DATE          DATE,
    RECOMMENDED_FOR         NVARCHAR2(200),
    VERIFICATION_STATUS     CHAR(1) DEFAULT 'N' NOT NULL, -- N:미인증, W:대기, Y:승인, R:거부
    STATUS                  CHAR(1) DEFAULT 'A' NOT NULL,  -- A:활성, D:삭제, B:차단
    CREATED_AT              DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT              DATE,
    CONSTRAINT PK_ACCOM_REVIEW PRIMARY KEY (REVIEW_NO),
    CONSTRAINT FK_AR_ACCOM FOREIGN KEY (ACCOMMODATION_NO)
        REFERENCES ACCOMMODATION(ACCOMMODATION_NO) ON DELETE CASCADE,
    CONSTRAINT FK_AR_MEMBER FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,
    CONSTRAINT FK_AR_BOARD FOREIGN KEY (BOARD_NO)
        REFERENCES BOARD(BOARD_NO) ON DELETE SET NULL,
    CONSTRAINT CHK_AR_RATING CHECK (RATING >= 1.0 AND RATING <= 5.0),
    CONSTRAINT CHK_AR_VERIFY CHECK (VERIFICATION_STATUS IN ('N', 'W', 'Y', 'R')),
    CONSTRAINT CHK_AR_STATUS CHECK (STATUS IN ('A', 'D', 'B')),
    CONSTRAINT CHK_AR_STAY CHECK (CHECK_IN_DATE IS NULL OR CHECK_OUT_DATE IS NULL OR CHECK_IN_DATE <= CHECK_OUT_DATE)
);

-- 후기 이미지
CREATE TABLE REVIEW_IMAGE (
    IMAGE_NO        NUMBER NOT NULL,
    REVIEW_NO       NUMBER NOT NULL,
    IMAGE_URL       VARCHAR2(500) NOT NULL,
    ORIGINAL_NAME   NVARCHAR2(200) NOT NULL,
    RENAMED_NAME    VARCHAR2(100) NOT NULL,
    IMAGE_ORDER     NUMBER DEFAULT 1 NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_REVIEW_IMAGE PRIMARY KEY (IMAGE_NO),
    CONSTRAINT FK_REVIEW_IMG_REVIEW FOREIGN KEY (REVIEW_NO)
        REFERENCES ACCOMMODATION_REVIEW(REVIEW_NO) ON DELETE CASCADE
);

-- 후기 숙박 인증 (예약 확인서 등)
CREATE TABLE REVIEW_VERIFICATION (
    VERIFICATION_NO     NUMBER NOT NULL,
    REVIEW_NO           NUMBER NOT NULL,
    VERIFICATION_FILE   VARCHAR2(500) NOT NULL,
    ORIGINAL_NAME       NVARCHAR2(200) NOT NULL,
    RENAMED_NAME        VARCHAR2(100) NOT NULL,
    SUBMITTED_AT        DATE DEFAULT SYSDATE NOT NULL,
    PROCESSED_AT        DATE,
    ADMIN_COMMENT       NVARCHAR2(500),
    CONSTRAINT PK_REVIEW_VERIFICATION PRIMARY KEY (VERIFICATION_NO),
    CONSTRAINT UK_REVIEW_VERIFY UNIQUE (REVIEW_NO),
    CONSTRAINT FK_VERIFY_REVIEW FOREIGN KEY (REVIEW_NO)
        REFERENCES ACCOMMODATION_REVIEW(REVIEW_NO) ON DELETE CASCADE
);

CREATE INDEX IDX_REVIEW_ACCOM ON ACCOMMODATION_REVIEW (ACCOMMODATION_NO, STATUS);
CREATE INDEX IDX_REVIEW_MEMBER ON ACCOMMODATION_REVIEW (MEMBER_NO);
CREATE INDEX IDX_REVIEW_STATUS_DATE ON ACCOMMODATION_REVIEW (STATUS, CREATED_AT DESC);


-- ================================================================
--  5. 동행 모집 게시판 도메인 (독립형)
-- ================================================================

CREATE SEQUENCE SEQ_COMPANION_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMPANION_JOIN_NO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 동행 모집 게시글
CREATE TABLE COMPANION_BOARD (
    COMPANION_NO     NUMBER PRIMARY KEY,
    TITLE            VARCHAR2(300) NOT NULL,
    CONTENT          VARCHAR2(4000) NOT NULL,
    IMAGE_URL        VARCHAR2(500),
    TRAVEL_DATE      VARCHAR2(50),
    MAX_MEMBERS      NUMBER DEFAULT 4,
    TAGS             VARCHAR2(500),
    STATUS           CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y','N','C')),  -- Y:모집중, N:삭제, C:마감
    MEMBER_NO        NUMBER NOT NULL REFERENCES MEMBER(MEMBER_NO),
    CREATED_AT       DATE DEFAULT SYSDATE,
    UPDATED_AT       DATE DEFAULT SYSDATE
);

-- 동행 참여 신청
CREATE TABLE COMPANION_JOIN (
    JOIN_NO          NUMBER PRIMARY KEY,
    COMPANION_NO     NUMBER NOT NULL REFERENCES COMPANION_BOARD(COMPANION_NO),
    MEMBER_NO        NUMBER NOT NULL REFERENCES MEMBER(MEMBER_NO),
    STATUS           CHAR(1) DEFAULT 'W' CHECK (STATUS IN ('W','A','R','C')),  -- W:대기, A:승인, R:거절, C:취소
    CREATED_AT       DATE DEFAULT SYSDATE
);

-- 동행 후기
CREATE TABLE COMPANION_REVIEW (
    REVIEW_NO        NUMBER PRIMARY KEY,
    COMPANION_NO     NUMBER NOT NULL REFERENCES COMPANION_BOARD(COMPANION_NO),
    MEMBER_NO        NUMBER NOT NULL REFERENCES MEMBER(MEMBER_NO),
    TITLE            VARCHAR2(300) NOT NULL,
    CONTENT          VARCHAR2(4000),
    RATING           NUMBER DEFAULT 5,
    IMAGE_URL        VARCHAR2(500),
    CONTENT_IMAGES   VARCHAR2(4000),
    STATUS           CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y','N')),  -- Y:정상, N:삭제
    CREATED_AT       DATE DEFAULT SYSDATE,
    UPDATED_AT       DATE DEFAULT SYSDATE
);


-- ================================================================
--  6. 채팅 도메인
-- ================================================================

CREATE SEQUENCE SEQ_CHATTING_ROOM_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MESSAGE_NO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 채팅방
CREATE TABLE CHATTING_ROOM (
    CHATTING_ROOM_NO NUMBER PRIMARY KEY,
    CREATE_DATE      DATE DEFAULT SYSDATE,
    OPEN_MEMBER      NUMBER NOT NULL REFERENCES MEMBER(MEMBER_NO),
    PARTICIPANT      NUMBER NOT NULL REFERENCES MEMBER(MEMBER_NO)
);

-- 메시지
CREATE TABLE MESSAGE (
    MESSAGE_NO       NUMBER PRIMARY KEY,
    MESSAGE_CONTENT  VARCHAR2(4000) NOT NULL,
    READ_FL          CHAR(1) DEFAULT 'N' CHECK (READ_FL IN ('Y','N')),
    SEND_TIME        DATE DEFAULT SYSDATE,
    SENDER_NO        NUMBER NOT NULL REFERENCES MEMBER(MEMBER_NO),
    CHATTING_ROOM_NO NUMBER NOT NULL REFERENCES CHATTING_ROOM(CHATTING_ROOM_NO)
);


-- ================================================================
--  7. 상호작용 도메인 (좋아요 / 북마크 / 스크랩)
-- ================================================================

CREATE SEQUENCE SEQ_BOARD_LIKE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_LIKE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BOOKMARK_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BOARD_SCRAP_NO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 게시글 좋아요
CREATE TABLE BOARD_LIKE (
    LIKE_NO         NUMBER NOT NULL,
    BOARD_NO        NUMBER NOT NULL,
    MEMBER_NO       NUMBER NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_BOARD_LIKE PRIMARY KEY (LIKE_NO),
    CONSTRAINT UK_BOARD_LIKE UNIQUE (BOARD_NO, MEMBER_NO),
    CONSTRAINT FK_BL_BOARD FOREIGN KEY (BOARD_NO)
        REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,
    CONSTRAINT FK_BL_MEMBER FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
);

-- 댓글 좋아요
CREATE TABLE COMMENT_LIKE (
    LIKE_NO         NUMBER NOT NULL,
    COMMENT_NO      NUMBER NOT NULL,
    MEMBER_NO       NUMBER NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_COMMENT_LIKE PRIMARY KEY (LIKE_NO),
    CONSTRAINT UK_COMMENT_LIKE UNIQUE (COMMENT_NO, MEMBER_NO),
    CONSTRAINT FK_CL_COMMENT FOREIGN KEY (COMMENT_NO)
        REFERENCES COMMENT_TBL(COMMENT_NO) ON DELETE CASCADE,
    CONSTRAINT FK_CL_MEMBER FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
);

-- 북마크
CREATE TABLE BOOKMARK (
    BOOKMARK_NO     NUMBER NOT NULL,
    BOARD_NO        NUMBER NOT NULL,
    MEMBER_NO       NUMBER NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_BOOKMARK PRIMARY KEY (BOOKMARK_NO),
    CONSTRAINT UK_BOOKMARK UNIQUE (BOARD_NO, MEMBER_NO),
    CONSTRAINT FK_BOOKMARK_BOARD FOREIGN KEY (BOARD_NO)
        REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,
    CONSTRAINT FK_BOOKMARK_MEMBER FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
);

-- 스크랩
CREATE TABLE BOARD_SCRAP (
    SCRAP_NO        NUMBER NOT NULL,
    BOARD_NO        NUMBER NOT NULL,
    MEMBER_NO       NUMBER NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_BOARD_SCRAP PRIMARY KEY (SCRAP_NO),
    CONSTRAINT UK_BOARD_SCRAP UNIQUE (BOARD_NO, MEMBER_NO),
    CONSTRAINT FK_BS_BOARD FOREIGN KEY (BOARD_NO)
        REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,
    CONSTRAINT FK_BS_MEMBER FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
);


-- ================================================================
--  8. 신고 도메인
-- ================================================================

CREATE SEQUENCE SEQ_BOARD_REPORT_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_REPORT_NO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 게시글 신고
CREATE TABLE BOARD_REPORT (
    REPORT_NO       NUMBER NOT NULL,
    BOARD_NO        NUMBER NOT NULL,
    MEMBER_NO       NUMBER NOT NULL,
    REPORT_TYPE     VARCHAR2(20) NOT NULL,               -- SPAM/ABUSE/FALSE_INFO/ADULT/ETC
    DETAIL_REASON   CLOB,
    STATUS          CHAR(1) DEFAULT 'P' NOT NULL,        -- P:대기, I:검토중, C:완료, R:반려
    RESULT          CLOB,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE,
    CONSTRAINT PK_BOARD_REPORT PRIMARY KEY (REPORT_NO),
    CONSTRAINT UK_BOARD_REPORT UNIQUE (BOARD_NO, MEMBER_NO),
    CONSTRAINT FK_BR_BOARD FOREIGN KEY (BOARD_NO)
        REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,
    CONSTRAINT FK_BR_MEMBER FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,
    CONSTRAINT CHK_BR_TYPE CHECK (REPORT_TYPE IN ('SPAM', 'ABUSE', 'FALSE_INFO', 'ADULT', 'ETC')),
    CONSTRAINT CHK_BR_STATUS CHECK (STATUS IN ('P', 'I', 'C', 'R'))
);

-- 댓글 신고
CREATE TABLE COMMENT_REPORT (
    REPORT_NO       NUMBER NOT NULL,
    COMMENT_NO      NUMBER NOT NULL,
    MEMBER_NO       NUMBER NOT NULL,
    REPORT_TYPE     VARCHAR2(20) NOT NULL,               -- SPAM/ABUSE/FALSE_INFO/ADULT/ETC
    DETAIL_REASON   CLOB,
    STATUS          CHAR(1) DEFAULT 'P' NOT NULL,        -- P:대기, I:검토중, C:완료, R:반려
    RESULT          CLOB,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE,
    CONSTRAINT PK_COMMENT_REPORT PRIMARY KEY (REPORT_NO),
    CONSTRAINT UK_COMMENT_REPORT UNIQUE (COMMENT_NO, MEMBER_NO),
    CONSTRAINT FK_CR_COMMENT FOREIGN KEY (COMMENT_NO)
        REFERENCES COMMENT_TBL(COMMENT_NO) ON DELETE CASCADE,
    CONSTRAINT FK_CR_MEMBER FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,
    CONSTRAINT CHK_CR_TYPE CHECK (REPORT_TYPE IN ('SPAM', 'ABUSE', 'FALSE_INFO', 'ADULT', 'ETC')),
    CONSTRAINT CHK_CR_STATUS CHECK (STATUS IN ('P', 'I', 'C', 'R'))
);

CREATE INDEX IDX_BR_STATUS ON BOARD_REPORT (STATUS, CREATED_AT DESC);
CREATE INDEX IDX_CR_STATUS ON COMMENT_REPORT (STATUS, CREATED_AT DESC);


-- ================================================================
--  8-1. 통합 신고 도메인
-- ================================================================

CREATE SEQUENCE SEQ_CONTENT_REPORT_NO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 통합 신고 (자유게시판/동행/후기 등)
CREATE TABLE CONTENT_REPORT (
    REPORT_NO       NUMBER NOT NULL,
    TARGET_TYPE     VARCHAR2(20) NOT NULL,
    TARGET_NO       NUMBER NOT NULL,
    MEMBER_NO       NUMBER NOT NULL,
    REPORT_TYPE     VARCHAR2(20) NOT NULL,
    DETAIL_REASON   CLOB,
    STATUS          CHAR(1) DEFAULT 'P' NOT NULL,
    RESULT          CLOB,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE,
    CONSTRAINT PK_CONT_REPORT PRIMARY KEY (REPORT_NO),
    CONSTRAINT FK_CONT_RPT_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,
    CONSTRAINT UK_CONT_REPORT UNIQUE (TARGET_TYPE, TARGET_NO, MEMBER_NO),
    CONSTRAINT CHK_CONT_RPT_TARGET CHECK (TARGET_TYPE IN ('FREEBOARD', 'COMPANION', 'REVIEW')),
    CONSTRAINT CHK_CONT_RPT_RTYPE CHECK (REPORT_TYPE IN ('SPAM', 'ABUSE', 'FALSE_INFO', 'ADULT', 'ETC')),
    CONSTRAINT CHK_CONT_RPT_STATUS CHECK (STATUS IN ('P', 'I', 'C', 'R'))
);

CREATE INDEX IDX_CONT_RPT_STATUS_DATE ON CONTENT_REPORT (STATUS, CREATED_AT DESC);
CREATE INDEX IDX_CONT_RPT_TARGET ON CONTENT_REPORT (TARGET_TYPE, TARGET_NO);


-- ================================================================
--  9. FAQ 도메인
-- ================================================================

CREATE SEQUENCE SEQ_FAQ_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FAQ_CATEGORY_NO START WITH 1 INCREMENT BY 1 NOCACHE;

-- FAQ 카테고리
CREATE TABLE FAQ_CATEGORY (
    CATEGORY_NO     NUMBER NOT NULL,
    CATEGORY_CODE   VARCHAR2(20) NOT NULL,
    CATEGORY_NAME   NVARCHAR2(100) NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_FAQ_CATEGORY PRIMARY KEY (CATEGORY_NO),
    CONSTRAINT UK_FAQ_CATEGORY_CODE UNIQUE (CATEGORY_CODE),
    CONSTRAINT UK_FAQ_CATEGORY_NAME UNIQUE (CATEGORY_NAME)
);

-- FAQ
CREATE TABLE FAQ (
    FAQ_NO          NUMBER NOT NULL,
    CATEGORY_NO     NUMBER NOT NULL,
    QUESTION        NVARCHAR2(500) NOT NULL,
    ANSWER          CLOB NOT NULL,
    DISPLAY_ORDER   NUMBER DEFAULT 1 NOT NULL,
    VIEW_COUNT      NUMBER DEFAULT 0 NOT NULL,
    STATUS          CHAR(1) DEFAULT 'A' NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE,
    CONSTRAINT PK_FAQ PRIMARY KEY (FAQ_NO),
    CONSTRAINT FK_FAQ_CATEGORY FOREIGN KEY (CATEGORY_NO)
        REFERENCES FAQ_CATEGORY(CATEGORY_NO) ON DELETE CASCADE,
    CONSTRAINT CHK_FAQ_STATUS CHECK (STATUS IN ('A', 'D'))
);


-- ================================================================
--  10. 명소 도메인
-- ================================================================

CREATE SEQUENCE SEQ_SPOT_NO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SPOT (
    SPOT_NO         NUMBER NOT NULL,
    SPOT_TITLE      VARCHAR2(100),
    SPOT_DESC       VARCHAR2(500),
    SPOT_LOCATION   VARCHAR2(100),
    SPOT_IMAGE      VARCHAR2(500),
    SPOT_TAG        VARCHAR2(50),
    SPOT_ORDER      NUMBER,
    SPOT_SIZE       VARCHAR2(20) DEFAULT 'small',
    SPOT_STATUS     VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_AT      DATE DEFAULT SYSDATE,
    UPDATED_AT      DATE,
    CONSTRAINT PK_SPOT PRIMARY KEY (SPOT_NO)
);

-- 기존 DB에 SPOT 테이블이 이미 있는 경우 아래 ALTER TABLE 실행:
-- ALTER TABLE SPOT ADD (SPOT_SIZE VARCHAR2(20) DEFAULT 'small');
-- ALTER TABLE SPOT ADD (SPOT_STATUS VARCHAR2(20) DEFAULT 'ACTIVE');
-- ALTER TABLE SPOT ADD (UPDATED_AT DATE);


-- ================================================================
--  11. 초기 데이터
-- ================================================================

-- 게시판 종류
INSERT INTO BOARD_TYPE (BOARD_CODE, BOARD_NAME) VALUES ('REVIEW', '후기 게시판');
INSERT INTO BOARD_TYPE (BOARD_CODE, BOARD_NAME) VALUES ('MATE', '동행 게시판');
INSERT INTO BOARD_TYPE (BOARD_CODE, BOARD_NAME) VALUES ('FREE', '자유 게시판');
INSERT INTO BOARD_TYPE (BOARD_CODE, BOARD_NAME) VALUES ('NOTICE', '공지사항');
INSERT INTO BOARD_TYPE (BOARD_CODE, BOARD_NAME) VALUES ('FAQ', 'FAQ');
INSERT INTO BOARD_TYPE (BOARD_CODE, BOARD_NAME) VALUES ('ACTIVITY', '행사/액티비티 게시판');

-- FAQ 카테고리
INSERT INTO FAQ_CATEGORY (CATEGORY_NO, CATEGORY_CODE, CATEGORY_NAME) VALUES (SEQ_FAQ_CATEGORY_NO.NEXTVAL, 'MEMBER', '회원');
INSERT INTO FAQ_CATEGORY (CATEGORY_NO, CATEGORY_CODE, CATEGORY_NAME) VALUES (SEQ_FAQ_CATEGORY_NO.NEXTVAL, 'ACCOM', '숙소');
INSERT INTO FAQ_CATEGORY (CATEGORY_NO, CATEGORY_CODE, CATEGORY_NAME) VALUES (SEQ_FAQ_CATEGORY_NO.NEXTVAL, 'BOARD', '커뮤니티');
INSERT INTO FAQ_CATEGORY (CATEGORY_NO, CATEGORY_CODE, CATEGORY_NAME) VALUES (SEQ_FAQ_CATEGORY_NO.NEXTVAL, 'ETC', '기타');

-- FAQ 초기 데이터 (서브쿼리로 CATEGORY_NO 조회 — DDL/실제 DB 모두 호환)

-- 회원 관련
INSERT INTO FAQ (FAQ_NO, CATEGORY_NO, QUESTION, ANSWER, DISPLAY_ORDER)
VALUES (SEQ_FAQ_NO.NEXTVAL, (SELECT CATEGORY_NO FROM FAQ_CATEGORY WHERE CATEGORY_CODE = 'MEMBER'), '회원가입은 어떻게 하나요?', '혼디 홈페이지 우측 상단의 "회원가입" 버튼을 클릭하여 이메일, 비밀번호, 닉네임 등 필수 정보를 입력하시면 간편하게 가입할 수 있습니다. 카카오 계정을 이용한 소셜 로그인도 지원하고 있어 더욱 빠르게 시작하실 수 있습니다.', 1);
INSERT INTO FAQ (FAQ_NO, CATEGORY_NO, QUESTION, ANSWER, DISPLAY_ORDER)
VALUES (SEQ_FAQ_NO.NEXTVAL, (SELECT CATEGORY_NO FROM FAQ_CATEGORY WHERE CATEGORY_CODE = 'MEMBER'), '비밀번호를 잊어버렸어요. 어떻게 찾나요?', '로그인 페이지 하단의 "비밀번호 찾기"를 클릭한 후, 가입 시 등록한 이메일 주소를 입력해 주세요. 해당 이메일로 비밀번호 재설정 링크가 발송됩니다. 메일이 오지 않는 경우 스팸함을 확인해 주세요.', 2);
INSERT INTO FAQ (FAQ_NO, CATEGORY_NO, QUESTION, ANSWER, DISPLAY_ORDER)
VALUES (SEQ_FAQ_NO.NEXTVAL, (SELECT CATEGORY_NO FROM FAQ_CATEGORY WHERE CATEGORY_CODE = 'MEMBER'), '카카오 계정으로도 로그인할 수 있나요?', '네, 혼디는 카카오 소셜 로그인을 지원합니다. 로그인 페이지에서 "카카오로 시작하기" 버튼을 누르면 카카오 계정으로 간편하게 로그인할 수 있습니다. 처음 이용 시 자동으로 회원가입이 진행됩니다.', 3);

-- 숙소 관련
INSERT INTO FAQ (FAQ_NO, CATEGORY_NO, QUESTION, ANSWER, DISPLAY_ORDER)
VALUES (SEQ_FAQ_NO.NEXTVAL, (SELECT CATEGORY_NO FROM FAQ_CATEGORY WHERE CATEGORY_CODE = 'ACCOM'), '숙소 예약은 어떻게 하나요?', '혼디에서 원하는 숙소를 검색한 후, 숙소 상세 페이지에서 날짜와 인원을 선택하고 "예약하기" 버튼을 클릭하시면 됩니다. 결제 완료 후 예약 확인 내역은 마이페이지에서 확인하실 수 있습니다.', 1);
INSERT INTO FAQ (FAQ_NO, CATEGORY_NO, QUESTION, ANSWER, DISPLAY_ORDER)
VALUES (SEQ_FAQ_NO.NEXTVAL, (SELECT CATEGORY_NO FROM FAQ_CATEGORY WHERE CATEGORY_CODE = 'ACCOM'), '숙소 예약을 취소하고 싶어요.', '마이페이지 > 예약 내역에서 해당 숙소의 "예약 취소" 버튼을 클릭하시면 됩니다. 취소 수수료는 숙소별 환불 정책에 따라 다르며, 체크인 3일 전까지는 무료 취소가 가능합니다. 자세한 환불 규정은 각 숙소의 상세 페이지를 참고해 주세요.', 2);
INSERT INTO FAQ (FAQ_NO, CATEGORY_NO, QUESTION, ANSWER, DISPLAY_ORDER)
VALUES (SEQ_FAQ_NO.NEXTVAL, (SELECT CATEGORY_NO FROM FAQ_CATEGORY WHERE CATEGORY_CODE = 'ACCOM'), '혼행(혼자 여행)에 추천하는 숙소 유형이 있나요?', '혼디에서는 혼행러를 위한 게스트하우스, 호스텔, 1인 독채 등 다양한 숙소를 추천하고 있습니다. 숙소 목록에서 "혼행추천" 태그가 붙은 숙소를 확인해 보세요. 다른 혼행러들의 후기도 함께 참고하시면 도움이 됩니다.', 3);

-- 커뮤니티 관련
INSERT INTO FAQ (FAQ_NO, CATEGORY_NO, QUESTION, ANSWER, DISPLAY_ORDER)
VALUES (SEQ_FAQ_NO.NEXTVAL, (SELECT CATEGORY_NO FROM FAQ_CATEGORY WHERE CATEGORY_CODE = 'BOARD'), '동행 모집은 어떻게 하나요?', '상단 메뉴의 "커뮤니티" > "동행 게시판"에서 새 글을 작성하시면 됩니다. 여행 일정, 목적지, 원하는 동행 스타일 등을 자세히 적어주시면 더 잘 맞는 동행을 찾으실 수 있습니다. 채팅 기능을 통해 동행 신청자와 미리 대화해 보세요.', 1);
INSERT INTO FAQ (FAQ_NO, CATEGORY_NO, QUESTION, ANSWER, DISPLAY_ORDER)
VALUES (SEQ_FAQ_NO.NEXTVAL, (SELECT CATEGORY_NO FROM FAQ_CATEGORY WHERE CATEGORY_CODE = 'BOARD'), '게시글에 사진을 첨부할 수 있나요?', '네, 게시글 작성 시 이미지 첨부가 가능합니다. 에디터 하단의 이미지 아이콘을 클릭하여 사진을 업로드하실 수 있으며, 최대 5장까지 첨부 가능합니다. 지원 형식은 JPG, PNG, GIF입니다.', 2);
INSERT INTO FAQ (FAQ_NO, CATEGORY_NO, QUESTION, ANSWER, DISPLAY_ORDER)
VALUES (SEQ_FAQ_NO.NEXTVAL, (SELECT CATEGORY_NO FROM FAQ_CATEGORY WHERE CATEGORY_CODE = 'BOARD'), '부적절한 게시글을 발견했어요. 신고는 어떻게 하나요?', '해당 게시글 우측 상단의 "신고" 버튼(깃발 아이콘)을 클릭하시면 신고 사유를 선택하여 접수할 수 있습니다. 신고 내역은 관리자가 검토 후 적절한 조치를 취합니다. 허위 신고를 반복할 경우 이용이 제한될 수 있으니 유의해 주세요.', 3);

-- 기타
INSERT INTO FAQ (FAQ_NO, CATEGORY_NO, QUESTION, ANSWER, DISPLAY_ORDER)
VALUES (SEQ_FAQ_NO.NEXTVAL, (SELECT CATEGORY_NO FROM FAQ_CATEGORY WHERE CATEGORY_CODE = 'ETC'), '혼디(HONDI)는 어떤 서비스인가요?', '혼디(HONDI)는 "혼자 + 제주 방언 혼디(함께)"를 결합한 이름으로, 제주도 혼자 여행(혼행)을 즐기는 분들을 위한 올인원 여행 플랫폼입니다. 숙소 검색 및 예약, 여행 명소 추천, 동행 모집, 커뮤니티 등 혼행에 필요한 모든 서비스를 제공합니다.', 1);
INSERT INTO FAQ (FAQ_NO, CATEGORY_NO, QUESTION, ANSWER, DISPLAY_ORDER)
VALUES (SEQ_FAQ_NO.NEXTVAL, (SELECT CATEGORY_NO FROM FAQ_CATEGORY WHERE CATEGORY_CODE = 'ETC'), '제주도 여행 시 대중교통은 어떻게 이용하나요?', '제주도는 버스 노선이 잘 갖추어져 있어 대중교통만으로도 주요 관광지를 방문할 수 있습니다. 카카오맵이나 네이버 지도 앱에서 버스 노선 및 시간을 검색하시면 편리합니다. 급행버스(빨간색)는 공항과 주요 지역을 빠르게 연결하며, 일반버스(파란색)는 세부 지역까지 운행합니다.', 2);
INSERT INTO FAQ (FAQ_NO, CATEGORY_NO, QUESTION, ANSWER, DISPLAY_ORDER)
VALUES (SEQ_FAQ_NO.NEXTVAL, (SELECT CATEGORY_NO FROM FAQ_CATEGORY WHERE CATEGORY_CODE = 'ETC'), '고객센터 운영시간은 어떻게 되나요?', '혼디 고객센터는 평일 오전 9시부터 오후 6시까지 운영됩니다(주말·공휴일 휴무). 문의사항은 홈페이지 하단의 "문의하기"를 통해 접수하실 수 있으며, 영업일 기준 1~2일 이내에 답변 드립니다. 긴급한 문의는 카카오톡 채널 "혼디"로 문의해 주세요.', 3);

-- 여행 스타일
INSERT INTO TRAVEL_STYLE (STYLE_NO, STYLE_NAME, DESCRIPTION) VALUES (SEQ_TRAVEL_STYLE_NO.NEXTVAL, '조용한', '혼자만의 시간을 즐기는 스타일');
INSERT INTO TRAVEL_STYLE (STYLE_NO, STYLE_NAME, DESCRIPTION) VALUES (SEQ_TRAVEL_STYLE_NO.NEXTVAL, '활발한', '사람들과 어울리기 좋아하는 스타일');
INSERT INTO TRAVEL_STYLE (STYLE_NO, STYLE_NAME, DESCRIPTION) VALUES (SEQ_TRAVEL_STYLE_NO.NEXTVAL, '사진좋아함', '인증샷을 남기는 스타일');
INSERT INTO TRAVEL_STYLE (STYLE_NO, STYLE_NAME, DESCRIPTION) VALUES (SEQ_TRAVEL_STYLE_NO.NEXTVAL, '맛집탐방', '맛집 찾아다니는 스타일');
INSERT INTO TRAVEL_STYLE (STYLE_NO, STYLE_NAME, DESCRIPTION) VALUES (SEQ_TRAVEL_STYLE_NO.NEXTVAL, '힐링추구', '여유로운 휴식을 추구하는 스타일');

-- 숙소 태그
INSERT INTO ACCOMMODATION_TAG (TAG_NO, TAG_NAME) VALUES (SEQ_ACCOM_TAG_NO.NEXTVAL, '조식제공');
INSERT INTO ACCOMMODATION_TAG (TAG_NO, TAG_NAME) VALUES (SEQ_ACCOM_TAG_NO.NEXTVAL, '주차가능');
INSERT INTO ACCOMMODATION_TAG (TAG_NO, TAG_NAME) VALUES (SEQ_ACCOM_TAG_NO.NEXTVAL, 'WiFi무료');
INSERT INTO ACCOMMODATION_TAG (TAG_NO, TAG_NAME) VALUES (SEQ_ACCOM_TAG_NO.NEXTVAL, '도미토리');
INSERT INTO ACCOMMODATION_TAG (TAG_NO, TAG_NAME) VALUES (SEQ_ACCOM_TAG_NO.NEXTVAL, '개인실');
INSERT INTO ACCOMMODATION_TAG (TAG_NO, TAG_NAME) VALUES (SEQ_ACCOM_TAG_NO.NEXTVAL, '오션뷰');
INSERT INTO ACCOMMODATION_TAG (TAG_NO, TAG_NAME) VALUES (SEQ_ACCOM_TAG_NO.NEXTVAL, '혼행추천');

COMMIT;


-- ================================================================
--  12. 숙소 유형 재분류 (기존 데이터가 있는 경우)
-- ================================================================

UPDATE ACCOMMODATION SET ACCOMMODATION_TYPE =
    CASE
        WHEN LOWER(NAME) LIKE '%호텔%' OR LOWER(NAME) LIKE '%hotel%' THEN '호텔'
        WHEN LOWER(NAME) LIKE '%리조트%' OR LOWER(NAME) LIKE '%resort%' THEN '리조트'
        WHEN LOWER(NAME) LIKE '%펜션%' OR LOWER(NAME) LIKE '%pension%' THEN '펜션'
        WHEN LOWER(NAME) LIKE '%풀빌라%' OR LOWER(NAME) LIKE '%pool villa%' THEN '풀빌라'
        WHEN LOWER(NAME) LIKE '%게스트하우스%' OR LOWER(NAME) LIKE '%guesthouse%' OR LOWER(NAME) LIKE '%guest house%' THEN '게스트하우스'
        WHEN LOWER(NAME) LIKE '%호스텔%' OR LOWER(NAME) LIKE '%hostel%' THEN '호스텔'
        WHEN LOWER(NAME) LIKE '%한옥%' THEN '한옥'
        WHEN LOWER(NAME) LIKE '%모텔%' THEN '모텔'
        WHEN LOWER(NAME) LIKE '%민박%' THEN '민박'
        ELSE '민박'
    END
WHERE STATUS = 'A';

COMMIT;


-- ================================================================
--  13. 검증 쿼리
-- ================================================================

SELECT '게시판 종류' AS 구분, COUNT(*) AS 개수 FROM BOARD_TYPE
UNION ALL SELECT 'FAQ 카테고리', COUNT(*) FROM FAQ_CATEGORY
UNION ALL SELECT '여행 스타일', COUNT(*) FROM TRAVEL_STYLE
UNION ALL SELECT '숙소 태그', COUNT(*) FROM ACCOMMODATION_TAG;

SELECT ACCOMMODATION_TYPE, COUNT(*) AS CNT
FROM ACCOMMODATION
WHERE STATUS = 'A'
GROUP BY ACCOMMODATION_TYPE
ORDER BY CNT DESC;


-- ================================================================
--  14. 회원 인증 시스템 (인증뱃지)
-- ================================================================

-- MEMBER 테이블에 인증뱃지 컬럼 추가
-- ALTER TABLE MEMBER ADD (VERIFIED_REVIEWER CHAR(1) DEFAULT 'N');
-- ALTER TABLE MEMBER ADD CONSTRAINT CHK_VERIFIED_REVIEWER CHECK (VERIFIED_REVIEWER IN ('Y', 'N'));

-- 회원 인증 요청 테이블
CREATE SEQUENCE SEQ_MEMBER_VERIFY_NO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE MEMBER_VERIFICATION (
    VERIFICATION_NO   NUMBER PRIMARY KEY,
    MEMBER_NO         NUMBER NOT NULL REFERENCES MEMBER(MEMBER_NO),
    VERIFICATION_FILE VARCHAR2(500) NOT NULL,
    ORIGINAL_NAME     NVARCHAR2(200) NOT NULL,
    RENAMED_NAME      VARCHAR2(100) NOT NULL,
    STATUS            CHAR(1) DEFAULT 'W' NOT NULL CHECK (STATUS IN ('W','Y','R')),
    ADMIN_COMMENT     NVARCHAR2(500),
    SUBMITTED_AT      DATE DEFAULT SYSDATE,
    PROCESSED_AT      DATE,
    PROCESSED_BY      NUMBER REFERENCES MEMBER(MEMBER_NO)
);

CREATE INDEX IDX_MV_MEMBER ON MEMBER_VERIFICATION (MEMBER_NO);
CREATE INDEX IDX_MV_STATUS ON MEMBER_VERIFICATION (STATUS, SUBMITTED_AT DESC);

-- 기존 ACCOMMODATION_REVIEW에서 불필요 컬럼 정리
-- ALTER TABLE ACCOMMODATION_REVIEW DROP COLUMN VERIFICATION_STATUS;
-- ALTER TABLE ACCOMMODATION_REVIEW DROP COLUMN BOARD_NO;

-- 기존 REVIEW_VERIFICATION 테이블 삭제 (회원 단위 인증으로 대체)
-- DROP TABLE REVIEW_VERIFICATION CASCADE CONSTRAINTS;


-- ================================================================
--  15. 기존 DB 마이그레이션 (이미 DB가 있는 경우에만 필요한 SQL)
-- ================================================================

-- MEMBER 테이블에 BIRTH_DATE 컬럼 추가
-- ALTER TABLE MEMBER ADD (BIRTH_DATE DATE);

-- SPOT 테이블에 신규 컬럼 추가
-- ALTER TABLE SPOT ADD (SPOT_SIZE VARCHAR2(20) DEFAULT 'small');
-- ALTER TABLE SPOT ADD (SPOT_STATUS VARCHAR2(20) DEFAULT 'ACTIVE');
-- ALTER TABLE SPOT ADD (UPDATED_AT DATE);

-- COMPANION_REVIEW 테이블 생성 (없는 경우)
-- CREATE TABLE COMPANION_REVIEW (
--     REVIEW_NO        NUMBER PRIMARY KEY,
--     COMPANION_NO     NUMBER NOT NULL REFERENCES COMPANION_BOARD(COMPANION_NO),
--     MEMBER_NO        NUMBER NOT NULL REFERENCES MEMBER(MEMBER_NO),
--     TITLE            VARCHAR2(300) NOT NULL,
--     CONTENT          VARCHAR2(4000),
--     RATING           NUMBER DEFAULT 5,
--     IMAGE_URL        VARCHAR2(500),
--     CONTENT_IMAGES   VARCHAR2(4000),
--     STATUS           CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y','N')),
--     CREATED_AT       DATE DEFAULT SYSDATE,
--     UPDATED_AT       DATE DEFAULT SYSDATE
-- );

-- FAQ 테이블 마이그레이션 (CATEGORY_CODE → CATEGORY_NO 기반)
-- 기존 FAQ_CATEGORY/FAQ 테이블이 CATEGORY_CODE 기반이면 아래 실행:
-- DROP TABLE FAQ CASCADE CONSTRAINTS;
-- DROP TABLE FAQ_CATEGORY CASCADE CONSTRAINTS;
-- DROP SEQUENCE SEQ_FAQ_NO;
-- 이후 섹션 9의 DDL + 섹션 11의 INSERT를 다시 실행
