-- ============================================================
-- 동행 찜 테이블 (COMPANION_WISHLIST)
-- ============================================================
CREATE TABLE COMPANION_WISHLIST (
    WISHLIST_NO   NUMBER PRIMARY KEY,
    COMPANION_NO  NUMBER NOT NULL REFERENCES COMPANION_BOARD(COMPANION_NO) ON DELETE CASCADE,
    MEMBER_NO     NUMBER NOT NULL REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,
    CREATED_AT    DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UK_COMPANION_WISHLIST UNIQUE (COMPANION_NO, MEMBER_NO)
);
CREATE SEQUENCE SEQ_COMPANION_WISHLIST_NO START WITH 1 INCREMENT BY 1;

-- ============================================================
-- 후기 찜 테이블 (REVIEW_WISHLIST)
-- ============================================================
CREATE TABLE REVIEW_WISHLIST (
    WISHLIST_NO  NUMBER PRIMARY KEY,
    REVIEW_NO    NUMBER NOT NULL REFERENCES COMPANION_REVIEW(REVIEW_NO) ON DELETE CASCADE,
    MEMBER_NO    NUMBER NOT NULL REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,
    CREATED_AT   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UK_REVIEW_WISHLIST UNIQUE (REVIEW_NO, MEMBER_NO)
);
CREATE SEQUENCE SEQ_REVIEW_WISHLIST_NO START WITH 1 INCREMENT BY 1;
