-- ============================================================
-- 그룹 채팅 DDL
-- 실행 순서: 1 → 2 → 3 → 4
-- ============================================================


-- 1. 그룹 채팅방
CREATE TABLE GROUP_CHAT_ROOM (
    GROUP_ROOM_NO  NUMBER        PRIMARY KEY,
    COMPANION_NO   NUMBER        NOT NULL REFERENCES COMPANION_BOARD(COMPANION_NO),
    ROOM_NAME      VARCHAR2(200) NOT NULL,
    CREATED_AT     DATE          DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_GROUP_ROOM_NO
    START WITH 1
    INCREMENT BY 1
    NOCACHE;


-- 2. 그룹 참여자 (1행 = 1멤버·1룸)
CREATE TABLE GROUP_CHAT_MEMBER (
    GROUP_MEMBER_ID NUMBER PRIMARY KEY,
    GROUP_ROOM_NO   NUMBER NOT NULL REFERENCES GROUP_CHAT_ROOM(GROUP_ROOM_NO),
    MEMBER_NO       NUMBER NOT NULL REFERENCES MEMBER(MEMBER_NO),
    JOINED_AT       DATE   DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UK_GCM UNIQUE (GROUP_ROOM_NO, MEMBER_NO)
);

CREATE SEQUENCE SEQ_GROUP_MEMBER_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;


-- 3. 그룹 메시지 (기존 MESSAGE 테이블과 완전 분리)
CREATE TABLE GROUP_MESSAGE (
    GROUP_MSG_NO  NUMBER         PRIMARY KEY,
    GROUP_ROOM_NO NUMBER         NOT NULL REFERENCES GROUP_CHAT_ROOM(GROUP_ROOM_NO),
    SENDER_NO     NUMBER         NOT NULL REFERENCES MEMBER(MEMBER_NO),
    MSG_CONTENT   VARCHAR2(4000) NOT NULL,
    SEND_TIME     DATE           DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_GROUP_MSG_NO
    START WITH 1
    INCREMENT BY 1
    NOCACHE;


-- 4. 읽음 워터마크 (사용자별 마지막 읽은 MSG_NO 저장)
CREATE TABLE GROUP_MSG_READ (
    READ_ID       NUMBER PRIMARY KEY,
    GROUP_ROOM_NO NUMBER NOT NULL REFERENCES GROUP_CHAT_ROOM(GROUP_ROOM_NO),
    MEMBER_NO     NUMBER NOT NULL REFERENCES MEMBER(MEMBER_NO),
    LAST_READ_MSG NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT UK_GMR UNIQUE (GROUP_ROOM_NO, MEMBER_NO)
);

CREATE SEQUENCE SEQ_GROUP_READ_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
